mali: don't use the return value seq_printf
Commit 6798a8caaf64 ("fs/seq_file: convert int seq_vprint/seq_printf/etc...
returns to void") changed the function return value to void to prevent
misuse of it. Adapt the mali gpu-memory-debugfs to prevent errors like

drivers/gpu/arm/midgard/mali_kbase_gpu_memory_debugfs.c: In function ‘kbasep_gpu_memory_seq_show’:
drivers/gpu/arm/midgard/mali_kbase_gpu_memory_debugfs.c:46:7: error: void value not ignored as it ought to be
   ret = seq_printf(sfile, "%-16s  %10u\n",
       ^
drivers/gpu/arm/midgard/mali_kbase_gpu_memory_debugfs.c:53:8: error: void value not ignored as it ought to be
    ret = seq_printf(sfile, "  %s-0x%p %10u\n",
        ^